# Generated by Django 4.0.1 on 2022-01-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statApp', '0002_remove_onedaydata_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Название города')),
            ],
        ),
        migrations.AddField(
            model_name='onedaydata',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='statApp.citylist'),
        ),
    ]
